"""Schemas for events, evidence, rules, and LLM suggestions."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class EvidenceRef(BaseModel):
    """A link from a field to document evidence."""

    doc_id: str
    page: int | None = None
    element_id: str | None = None
    quote: str | None = None
    field_name: str


class LlmSuggestion(BaseModel):
    """Structured suggestion generated by the LLM layer."""

    recommendation_text: str
    reasoning_summary: str
    confidence_hint: str = "medium"
    risk_level: str | None = None
    needs_manual_review: bool | None = None
    model_name: str
    provider_name: str
    used_mock: bool = False


class ConjunctionEvent(BaseModel):
    """Canonical event structure used across the pipeline."""

    event_id: str
    message_id: str | None = None
    conjunction_id: str | None = None
    primary_object_name: str | None = None
    secondary_object_name: str | None = None
    primary_norad_id: str | None = None
    secondary_norad_id: str | None = None
    tca_utc: datetime | None = None
    miss_distance_m: float | None = None
    relative_speed_mps: float | None = None
    collision_probability: float | None = None
    reference_frame: str | None = None
    covariance_present: bool = False
    risk_level: str = "unknown"
    action_recommendation: str | None = None
    needs_manual_review: bool = False
    evidence_refs: list[EvidenceRef] = Field(default_factory=list)
    llm_suggestion: LlmSuggestion | None = None
    external_context: dict = Field(default_factory=dict)
    version_group_key: str | None = None
